apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-deploy
  labels:
    app: myflaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: prabhu12yuva/fsm-appx:myflaskapp1
        ports:
        - containerPort: 5000
